name: kisanone
description: A smart agriculture app
publish_to: 'none'

environment:
  sdk: ">=2.19.0 <3.0.0"   # ✅ supports your Dart 2.19.2

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.0
  image_picker: ^0.8.7+5
  http: ^0.13.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  speech_to_text: ^6.3.0
  geolocator: ^9.0.2
  weather: 3.0.0
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/translations/